const queryString = window.location.search;
const urlParams = new URLSearchParams(queryString);
const contentURL = urlParams.get('url');
document.getElementById('frame').src = contentURL;
const width =  Number(document.getElementById('frame').width);
const height = Number((width * (9 / 16)) - 300);
const titled = document.getElementById('frame').title;
document.getElementById('frame').height = height
document.title = titled;
